apiVersion: v1
kind: Secret
metadata:
  name: inboxready-secrets
  namespace: inboxready
type: Opaque
stringData:
  INBOXREADY_SESSION_SECRET: "replace-with-at-least-32-random-characters"
  INBOXREADY_STRIPE_SECRET_KEY: ""
  INBOXREADY_STRIPE_WEBHOOK_SECRET: ""
  INBOXREADY_STRIPE_STARTER_PRICE_ID: ""
  INBOXREADY_STRIPE_GROWTH_PRICE_ID: ""
  INBOXREADY_STRIPE_PRO_PRICE_ID: ""
