apiVersion: v1
kind: Service
metadata:
  name: inboxready-api
  namespace: inboxready
  labels:
    app: inboxready-api
spec:
  type: ClusterIP
  selector:
    app: inboxready-api
  ports:
    - name: http
      port: 80
      targetPort: http
